kind: Job
apiVersion: batch/v1
metadata:
  name: one-time-job
spec:
  template:
    spec:
      containers:
        - name: busybox-container
          image: busybox
          imagePullPolicy: IfNotPresent
          args:
            - /bin/sh
            - -c
            - date; sleep 20; echo "Bye"
      restartPolicy: OnFailure