kind: Pod
apiVersion: v1
metadata:
  name: multi-container-pod
spec:
  containers:
    - name: first-container
      image: nginx
      imagePullPolicy: IfNotPresent
    - name: second-container
      imagePullPolicy: IfNotPresent
      image: ubuntu
      command:
        - /bin/bash
        - -ce
        - while :; do echo "."; sleep 5; done