kind: Deployment
apiVersion: apps/v1
metadata:
  name: k8s-for-beginners
spec:
  replicas: 3
  selector:
    matchLabels:
      tier: frontend
  template:
    metadata:
      labels:
        tier: frontend
    spec:
      containers:
        - name: k8s-for-beginners
          imagePullPolicy: IfNotPresent
          image: packtworkshops/the-kubernetes-workshop:k8s-for-beginners
