kind: Service
apiVersion: v1
metadata:
  name: nginx-service-custom-clusterip
spec:
  type: ClusterIP
  clusterIP: 10.90.10.70
  selector:
    app: nginx
    environment: production
  ports:
    - port: 80
      targetPort: 80