apiVersion: v1
kind: Pod
metadata:
  name:  pod-with-exposed-port
spec:
  containers:
    - name: container-with-exposed-port
      image: nginx
      imagePullPolicy: IfNotPresent
      ports:
        - containerPort: 80